### ISSUE TITLE
are you swapping quadrants?

### ISSUE THREAD

**Issue by I3aer** [qq456cvb/deblur#1]
Hi,
Can you tell me what you are doing in the following lines?

    kernel[:half_ksize+1, :half_ksize+1] = k[:half_ksize+1, :half_ksize+1]
    kernel[-half_ksize:, -half_ksize:] = k[-half_ksize:, -half_ksize:]
    kernel[:half_ksize+1, -half_ksize:] = k[:half_ksize+1, -half_ksize:]
    kernel[-half_ksize:, :half_ksize+1] = k[-half_ksize:, :half_ksize+1]

this is same as kernel = k

**Comment by qq456cvb** [comment]
On L120, k is not necessarily zero outside the range, e.g. [:half_ksize+1, :half_ksize+1], so I am zeroing out these values using the prior that kernel should be narrowly localized.

**Comment by I3aer** [comment]
Thanks for the response. After recalling my knowledge about 2d fft, I think you just get low freq. content which is at the corners of the fft result. This is because that PSF is a low-pass filter.

**Comment by qq456cvb** [comment]
Exactly, we are assuming that the motion blur is a low-pass filter.
