### ISSUE TITLE
Phase Two Refinement Solving Eq.  (10) 

### ISSUE THREAD

**Issue by I3aer** [qq456cvb/deblur#2]
In the paper, the Eq. (10) is given by

E(k) = 0.5 * ||∇I^s ⊗ k − ∇B ||^2 + γ * sum_j∈\bar S_{i+1} |k_j|

The corresponding linear equation is given the Eq. by (11)

[A'A + γ * diag(V_{\bar S}Ψ^{-1})]V_k = A' V_{B},

In my view, the A must be expressed using ∇I^s (the selected edges for the kernel estimation) according to Eq. (10), but the paper says it is the matrix of the latent image I. In your code, you are using I_tilde_grad (gradient of the shock-filtered image). Could you explain why you use I_tilde_grad ?

**Comment by qq456cvb** [comment]
I think the paper has a typo here. You are right, it should be ∇I^s which is I_grad_s in the code. I don't remember why I use I_tilde_grad but you can replace it with I_grad_s.

**Comment by I3aer** [comment]
Thank you. You helped much about my questions on an old paper. Good luck!

On Tuesday, September 27, 2022, Yang You ***@***.***> wrote:
> I think the paper has a typo here. You are right, it should be ∇I^s which
is I_grad_s in the code. I don'tremember why I use I_tilde_grad but you can
replace it with I_grad_s.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci6.googleusercontent.com/proxy/VhSr3_07sBgW_9XMjTDyvk03vC_L-71FOajmqWCcI0WkehmQXywcKmdMjhxRgVC8TYQ14B1GMLvVz_ddZTKhPEIRAoT0f2KRCL-VYzIAwS6dXdmagqN6XzzO4ZhLenxDPmRR0RfnEtOZ1-bsgOVodxeYVyXfdNYcrQ-5StkSn-FWegRl8z20A7OfsEWIqr98zyARjhGffENGvyAA2fg55mbYADnlhESEvw5nGLnSUK4vmL6JHQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHZ4U3ESJTJ2WN5KNSJRLVDWAKO5NA5CNFSM6AAAAAAQLTTV4OWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSLBRIDC.gif>Message
ID: ***@***.***>
